name: Node.js CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/nodejs-repo:latest .

      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/nodejs-repo:latest

      # - name: Lint code
      #   run: npm run lint

      # - name: Run tests
      #   run: npm test

      # - run:
      #     name: Build Docker image
      #     command: |
      #       echo "Building Docker image"
      #       docker build -t "$DOCKER_USERNAME/node-app:latest" .

      # - run:
      #     name: Push Docker image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push "$DOCKER_USERNAME/node-app:latest"
